Avoid writing to the Django settings module
I originally made this change because some of Django's tests were failing with "AttributeError: 'Settings' object has no attribute 'ENCRYPTED_COOKIE_KEY'" when ran in the context of a particular project I work on that uses django-encrypted-cookie-session. After making this change I remembered that those tests had been failing (with different errors) before the ENCRYPTED_COOKIE_KEY code that I changed in this commit was introduced. However, it seems safer to avoid writing to the Django settings module anyway.